export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_BYID_REQUEST = 'GET_PRODUCT_BYID_REQUEST';
export const GET_PRODUCT_BYID_SUCCESS = 'GET_PRODUCT_BYID_SUCCESS';
export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL;';
